namespace: cisco
name: iosxr
version: 0.1.0
readme: README.md
authors: null
description: null
license: GPL-3.0-or-later
license_file: COPYING
tags: null
dependencies:
  ansible.netcommon: '>=0.1.0'
repository: git@github.com:coll-test/cisco.iosxr.git
documentation: https://github.com/coll-test/cisco.iosxr/tree/master/docs
homepage: https://github.com/coll-test/cisco.iosxr
issues: https://github.com/coll-test/cisco.iosxr/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
